### ISSUE TITLE
[Bug]: Latest GIT build as of May 8th, 2025 is unbuildable.

### ISSUE THREAD

**Issue by isaoyamasita** [WiVRn/WiVRn#331]
### Describe the bug

Compilation craps out at the follwoing.
Please see this screenchot from a terminal:

![Image](https://github.com/user-attachments/assets/008cfb3d-4b19-48f0-b928-b0dd25b7da33)

### Steps to Reproduce

1. In Arch, start installation and compilation by 'yay -Syu wivrn-full-git'.
2. The compilation process errors out with the error messages in the screenshot.
3. Looks like name changes for some #define(s).

### Expected behavior

The compilation should proceed to installation.

### WiVRn Version

d17fac3

### What GPU did the bug occur on?

AMD

### Vulkan Info

==========
VULKANINFO
==========

Vulkan Instance Version: 1.4.313

Instance Extensions: count = 24
-------------------------------
VK_EXT_acquire_drm_display             : extension revision 1
VK_EXT_acquire_xlib_display            : extension revision 1
VK_EXT_debug_report                    : extension revision 10
VK_EXT_debug_utils                     : extension revision 2
VK_EXT_direct_mode_display             : extension revision 1
VK_EXT_display_surface_counter         : extension revision 1
VK_EXT_headless_surface                : extension revision 1
VK_EXT_surface_maintenance1            : extension revision 1
VK_EXT_swapchain_colorspace            : extension revision 5
VK_KHR_device_group_creation           : extension revision 1
VK_KHR_display                         : extension revision 23
VK_KHR_external_fence_capabilities     : extension revision 1
VK_KHR_external_memory_capabilities    : extension revision 1
VK_KHR_external_semaphore_capabilities : extension revision 1
VK_KHR_get_display_properties2         : extension revision 1
VK_KHR_get_physical_device_properties2 : extension revision 2
VK_KHR_get_surface_capabilities2       : extension revision 1
VK_KHR_portability_enumeration         : extension revision 1
VK_KHR_surface                         : extension revision 25
VK_KHR_surface_protected_capabilities  : extension revision 1
VK_KHR_wayland_surface                 : extension revision 6
VK_KHR_xcb_surface                     : extension revision 6
VK_KHR_xlib_surface                    : extension revision 6
VK_LUNARG_direct_driver_loading        : extension revision 1

Instance Layers: count = 9
--------------------------
VK_LAYER_INTEL_nullhw             INTEL NULL HW                1.1.73   version 1
VK_LAYER_MESA_device_select       Linux device selection layer 1.4.303  version 1
VK_LAYER_MESA_overlay             Mesa Overlay layer           1.4.303  version 1
VK_LAYER_MESA_screenshot          Mesa Screenshot layer        1.4.303  version 1
VK_LAYER_MESA_vram_report_limit   Limit reported VRAM          1.4.303  version 1
VK_LAYER_VALVE_steam_fossilize_32 Steam Pipeline Caching Layer 1.3.207  version 1
VK_LAYER_VALVE_steam_fossilize_64 Steam Pipeline Caching Layer 1.3.207  version 1
VK_LAYER_VALVE_steam_overlay_32   Steam Overlay Layer          1.3.207  version 1
VK_LAYER_VALVE_steam_overlay_64   Steam Overlay Layer          1.3.207  version 1

Devices:
========
GPU0:
apiVersion         = 1.4.305
driverVersion      = 25.0.5
vendorID           = 0x1002
deviceID           = 0x744c
deviceType         = PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
deviceName         = AMD Radeon RX 7900 XTX (RADV NAVI31)
driverID           = DRIVER_ID_MESA_RADV
driverName         = radv
driverInfo         = Mesa 25.0.5-arch1.1
conformanceVersion = 1.4.0.0
deviceUUID         = 00000000-0300-0000-0000-000000000000
driverUUID         = 414d442d-4d45-5341-2d44-525600000000
GPU1:
apiVersion         = 1.4.305
driverVersion      = 25.0.5
vendorID           = 0x1002
deviceID           = 0x13c0
deviceType         = PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
deviceName         = AMD Radeon Graphics (RADV RAPHAEL_MENDOCINO)
driverID           = DRIVER_ID_MESA_RADV
driverName         = radv
driverInfo         = Mesa 25.0.5-arch1.1
conformanceVersion = 1.4.0.0
deviceUUID         = 00000000-1a00-0000-0000-000000000000
driverUUID         = 414d442d-4d45-5341-2d44-525600000000
GPU2:
apiVersion         = 1.4.305
driverVersion      = 0.0.1
vendorID           = 0x10005
deviceID           = 0x0000
deviceType         = PHYSICAL_DEVICE_TYPE_CPU
deviceName         = llvmpipe (LLVM 19.1.7, 256 bits)
driverID           = DRIVER_ID_MESA_LLVMPIPE
driverName         = llvmpipe
driverInfo         = Mesa 25.0.5-arch1.1 (LLVM 19.1.7)
conformanceVersion = 1.3.1.1
deviceUUID         = 6d657361-3235-2e30-2e35-2d6172636800
driverUUID         = 6c6c766d-7069-7065-5555-494400000000

### What HMD did the bug occur on?

Quest

**Comment by xytovl** [comment]
This is in unmodified Monado code.

Do you get the same error building https://aur.archlinux.org/packages/monado-git?
In that case the issue shall be fixed in https://gitlab.freedesktop.org/monado/monado first, and I'll update the version we use.

The issue might also be an error in vulkan headers, with version 1.4.309.0 it works and they are not supposed to break source compatibility.

**Comment by xytovl** [comment]
https://gitlab.freedesktop.org/monado/monado/-/issues/514 opened

**Comment by isaoyamasita** [comment]
Yes, I just tried to recompile Monado and got the same errors.
It's strange that when I updated Monado yesterday, it compiled just fine.
The Vulkan headers has just updated today and I restarted my PC.

Screenshot below:
![Image](https://github.com/user-attachments/assets/57bb06e4-c95b-4eb4-8d87-8e9578cd15ec)

**Comment by Firepal** [comment]
Adding `#define VK_ENABLE_BETA_EXTENSIONS` to `monado-src/src/xrt/include/xrt/xrt_vulkan_includes.h` right before Vulkan is included allows Monado to build.

However, this reveals that WiVRn has issues with the `VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_ENQUEUE_PROPERTIES_AMDX` define

**Comment by Firepal** [comment]
My build with the Monado fix errors at `server/utils/wivrn_vk_bundle.h` where `#include <vulkan/vulkan_raii.hpp>` can't see Vulkan enums that it needs, now guarded by that "beta extensions" define. I tried adding the define before the vulkan include, but it does not fix it and I have no idea why.

**Comment by xytovl** [comment]
The following patch for Monado worked for me: 
```patch
diff --git a/src/xrt/auxiliary/vk/vk_helpers.c b/src/xrt/auxiliary/vk/vk_helpers.c
index a7a40e986..1159fbc33 100644
--- a/src/xrt/auxiliary/vk/vk_helpers.c
+++ b/src/xrt/auxiliary/vk/vk_helpers.c
@@ -247,10 +247,6 @@ vk_object_type_string(VkObjectType type)
 #ifdef VK_NV_device_generated_commands
 		ENUM_TO_STR(VK_OBJECT_TYPE_INDIRECT_COMMANDS_LAYOUT_NV);
 #endif
-#ifdef VK_NV_cuda_kernel_launch
-		ENUM_TO_STR(VK_OBJECT_TYPE_CUDA_MODULE_NV);
-		ENUM_TO_STR(VK_OBJECT_TYPE_CUDA_FUNCTION_NV);
-#endif
 #ifdef VK_FUCHSIA_buffer_collection
 		ENUM_TO_STR(VK_OBJECT_TYPE_BUFFER_COLLECTION_FUCHSIA);
 #endif
```

What is the error you have on `server/utils/wivrn_vk_bundle.h`?

**Comment by Firepal** [comment]
> What is the error you have on `server/utils/wivrn_vk_bundle.h`?

Well actually... The error occurs as `server/driver/wivrn_session.cpp` includes `server/driver/wivrn_comp_target.h`, which includes that `wivrn_vk_bundle.h` file, which include Vulkan libraries...

Just read the log...
https://pastebin.com/raw/xQLBYYYv

**Comment by isaoyamasita** [comment]
Has this issue been solved yet ? Has the patch for Monado by xytovl ever been submitted to an appropriate place ?

**Comment by xytovl** [comment]
No, the patch is a workaround and don't plan on integrating it, the root issue is in vulkan headers.

https://gitlab.khronos.org/vulkan/vulkan/-/issues/4281 was opened in the internal tracker but I don't have access.

I have opened https://github.com/KhronosGroup/Vulkan-Docs/issues/2531 in the public one but have no response yet.

**Comment by xytovl** [comment]
Pushed in https://github.com/WiVRn/WiVRn/tree/monado-update
I have to verify that it doesn't break bindings, I removed a patch that didn't apply but that shouldn't be needed anymore.

**Comment by xytovl** [comment]
fixed by 2225dafaf2b44fbe5d46a37252f2f16bdbfbee66
