### ISSUE TITLE
Server core dumps on connection

### ISSUE THREAD

**Issue by lever1209** [WiVRn/WiVRn#70]
ERROR [VideoEncoderNvenc] /usr/src/debug/wivrn-server/WiVRn-0.15/server/encoder/video_encoder_nvenc.cpp:279: 8, 
ERROR [comp_wivrn_create_images] Failed to create video encoder: TODO

(sorry for blank init, browser was having issues)

**Comment by Meumeu** [comment]
Can you post the entire server logs? There should be a more explicit error message just before that.

**Comment by lever1209** [comment]
```
WiVRn v0.0.0 starting
Removing stale socket file /run/user/1000/wivrn_comp_ipc
Service published: brazil
Server started, PID 12099
 INFO [ipc_server_main]  'v21.0.0-4402-gffb71af2' starting up...
DEBUG [comp_main_create_system_compositor] Doing init 0x59c6e89c2da0
 WARN [build_device_extensions] Duplicate device extension VK_KHR_external_memory_fd not added twice
 WARN [build_device_extensions] Duplicate device extension VK_KHR_external_memory_fd not added twice
 WARN [build_device_extensions] Duplicate device extension VK_KHR_external_memory_fd not added twice
 INFO [create_device] Created device and COMPUTE queue with QUEUE_GLOBAL_PRIORITY_MEDIUM.
 INFO [vk_print_device_info] Device info:
	name: NVIDIA GeForce RTX 3070
	vendor: 0x10de
	product: 0x2484
	deviceType: VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
	apiVersion: 1.3.277
	driverVersion: 0x89938000
 INFO [vk_print_features_info] Features:
	timestamp_compute_and_graphics: true
	timestamp_period: 1.000000
	timestamp_valid_bits: 64
	timeline_semaphore: true
 INFO [vk_print_external_handles_info] Supported images:
	VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT:
		color import=true export=true
		depth import=true export=true
 INFO [vk_print_external_handles_info] Supported fences:
	VK_EXTERNAL_FENCE_HANDLE_TYPE_SYNC_FD_BIT: true
	VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_FD_BIT: true
 INFO [vk_print_external_handles_info] Supported semaphores:
	VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_BIT(binary): true
	VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT(binary): true
	VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_BIT(timeline): false
	VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT(timeline): true
17 HEVC presets
  Preset {b2dfb705-4ebd-4c49-9b5f-24a777d3e587}
  Preset {49df21c5-6dfa-4feb-9787-6acc9effb726}
  Preset {60e4c59f-e846-4484-a56d-cd45be9fddf6}
  Preset {34dba71d-a77b-4b8f-9c3e-b6d5da24c012}
  Preset {82e3e450-bdbb-4e40-989c-82a90df9ef32}
  Preset {c5f733b9-ea97-4cf9-bec2-bf78a74fd105}
  Preset {67082a44-4bad-48fa-98ea-93056d150a58}
  Preset {7add423d-d035-4f6f-aea5-50885658643c}
  Preset {d5bfb716-c604-44e7-9bb8-dea5510fc3ac}
  Preset {149998e7-2364-411d-82ef-179888093409}
  Preset {fc0a8d3e-45f8-4cf8-80c7-298871590ebf}
  Preset {f581cfb8-88d6-4381-93f0-df13f9c27dab}
  Preset {36850110-3a07-441f-94d5-3670631f91f6}
  Preset {90a7b826-df06-4862-b9d2-cd6d73a08681}
  Preset {21c6e6b4-297a-4cba-998f-b6cbde72ade3}
  Preset {8e75c279-6299-4ab6-8302-0b215a335cf5}
  Preset {84848c12-6f71-4c13-931b-53e283f57974}
ERROR [VideoEncoderNvenc] /usr/src/debug/wivrn-server/WiVRn-0.15/server/encoder/video_encoder_nvenc.cpp:279: 8, 
ERROR [comp_wivrn_create_images] Failed to create video encoder: TODO
Server exited, exit status 0, received signal ABRT (Aborted), core dumped
Service published: brazil
```

i am unaware of any log file, so here is the stdout

**Comment by xytovl** [comment]
Should be fixed by https://github.com/Meumeu/WiVRn/commit/bef30c3b91bffe86b28ff9ad1127c8f1b0787cbc

**Comment by Okabintaro** [comment]
I had a similar error with my config, even with that commit.
The config looked like this:
```json
{
  "scale": [
    0.5,
    0.5
  ],
  "bitrate": 120000000,
  "encoders": [
    {
      "encoder": "nvenc",
      "codec": "h264",
      "width": 0.5,
      "height": 1.0,
      "offset_x": 0.0,
      "offset_y": 0.0
    },
    {
      "encoder": "nvenc",
      "codec": "h264",
      "width": 0.5,
      "height": 1.0,
      "offset_x": 0.5,
      "offset_y": 0.0
    }
  ]
}
```

But it turns out it was my config with the bit rate and sliced encoding that was setup wrong.
For me it was mostly failing at the end of the method here: https://github.com/Meumeu/WiVRn/blob/bef30c3b91bffe86b28ff9ad1127c8f1b0787cbc/server/encoder/video_encoder_nvenc.cpp#L298
This one work for me right now:

```json
{
  "scale": [
    0.7,
    0.7
  ],
  "bitrate": 100000000,
  "encoders": [
    {
      "encoder": "nvenc",
      "codec": "h264"
    }
  ],
  "tcp_only": true
}
```

All in all it is still a bit confusing what to configure how with nvenc. I hope that I can dig into a bit more and maybe write a guide on the limits of each field and the scale you can set now in the hmd settings.

**Comment by xytovl** [comment]
Can you check https://github.com/Meumeu/WiVRn/tree/fix/nvenc-color-scale branch?

There's 2 fixes: one for color (issue https://github.com/Meumeu/WiVRn/issues/74) and the other one for odd sizes, which is likely to be the issue here.

**Comment by Okabintaro** [comment]
I tried the branch and it still crashes for me on Quest with a scale in the HMD of 1.7(3144x3425).
```
ERROR [VideoEncoderNvenc] /home/oka/dev/repos/WiVRn2/server/encoder/video_encoder_nvenc.cpp:304: 8, 
nvenc error
```
1.0 worked fine though.

The patch from @galister that did this actually works though:

```c++
+       settings.video_width += 32 - settings.video_width % 32;
+       settings.video_height += 32 - settings.video_height % 32;
```

**Comment by xytovl** [comment]
I have pushed that fix on the branch too

**Comment by Okabintaro** [comment]
Yeah, I know, but your fix doesn't seem to suffice, making it just even, while the `% 32` seems to have worked.

**Comment by Okabintaro** [comment]
Yes seems to be fixed now! Now the question is if that is the same issue that @lever1209 had. You wanna give it a go too @lever1209?
